Onepage
IT-S-BMSTU/Robotechnics_SITE pull request #28
Opened 2024-05-06 09:02 UTC by Robocotik

Ready to be checked

2024-06-04 22:34 UTC, darleet requested changes
Нужно пофиксить шрифт, остальное все сделано отлично. Баги кинул в трекер

2024-06-04 22:34 UTC, darleet commented on Frontend/src/index.scss
> +  font-family: ALS Sector Regular, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
где-то здесь собака зарыта... может быть название все-таки было правильным? иначе странно, что шрифт перестал работать

2024-06-13 20:28 UTC, Robocotik commented on Frontend/src/index.scss
> +  font-family: ALS Sector Regular, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
Я честно говоря, ума не приложу почему это вещица у меня в начале работы не хотела als sector показывать. Краткая аналитика показала, что дело было во втором слове Regular. Щас это уже наоборот...

2024-06-13 20:55 UTC, Robocotik commented on Frontend/src/index.scss
> +  font-family: ALS Sector Regular, -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
проблема в том, что als sector regular не поддерживает жирность меньше 500, а у нас 400. Так что фактически дело именно в выборе этих словечек (regular) и их сочетании.

2024-06-23 12:57 UTC, Robocotik commented
Как я понимаю все, что надо было пофиксить, сделано + сделаны "серьезные" таски

2024-06-23 19:09 UTC, darleet approved these changes
Все ок

2024-06-23 19:10 UTC, merged