Delete pagination
IT-S-BMSTU/Robotechnics_SITE pull request #30
Opened 2024-05-06 11:50 UTC by Timur1414

2024-06-03 09:10 UTC, darleet requested changes
Нужно пофиксить нейминг для хардатонов, заменить `hardaton` на `hardathon`. В остальном все окей

2024-06-03 09:10 UTC, darleet commented on Django/robotechnics/hardathon/urls.py
> +    path('get_event_partners/<int:pk>/', HardatonPartnersViewSet.as_view()),
Везде по-разному называются хардатоны, нужно сделать нейминг консистентным: `hardathon`

```suggestion
    path('hardathons/', HardathonViewSet.as_view()),
    path('hardathons/<int:pk>/', HardathonViewSet.as_view()),
    path('project/<int:pk>/', HardathonProjectsViewSet.as_view()),
    path('projects/', HardathonProjectsViewSet.as_view()),
    path('get_event_partners/<int:pk>/', HardathonPartnersViewSet.as_view()),
```

2024-06-03 09:10 UTC, darleet commented on Django/robotechnics/hardathon/urls.py
> +                              HardatonPartnersViewSet)
Здесь та же ситуация с неймингом

```suggestion
from hardathon.router import (HardathonViewSet,
                              HardathonProjectsViewSet,
                              HardathonPartnersViewSet)
```

2024-06-03 09:10 UTC, darleet commented on Django/robotechnics/hardathon/router.py
> +        serializer = HardatonPartnersSerializer(instance=partners, many=True)
Нужно также пофиксить нейминг

2024-06-16 15:32 UTC, Timur1414 commented
@darleet готово.

2024-07-01 15:03 UTC, merged